### PR TITLE
Relax openjdk pin and build only once

### PR DESCRIPTION
**Pull request by mbiette**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This change relax the pin of openjdk. It is not clear to me why it is pinned so tightly when in my experience there is a wide range of jdk versions ant would successfully run with regardless of the build version. Here it still pins to the same major but it could be argued that any openjdk version higher than the build version could be fine.

### CODE REVIEW

**Comment by mbiette** [comment]
@conda-forge-admin, please rerender

**Comment by mbiette** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
What's the purpose of this PR? There hasn't been an openjdk with a non-zero minor version since at least v8, so whether we do `>=N.M,<{N+1}` or `>=N.M,<N.{M+1}` is functionally equivalent in that case.

**Comment by mbiette** [comment]
The main goal of that PR is to add a min_pin. Otherwise new packages get pinned to the latest minor `>=A.B.C,…`. i.e. the package built with openjdk 17 is pinned to >=17.0.8 currently. If you agree on the min_pin but prefer pin to x.x that’s fine too.

**Comment by h-vetinari** [comment]
> package built with openjdk 17 is pinned to >=17.0.8 currently.

That's standard and shouldn't have to change. Any given library that you're building might rely on bugfixes in those patch releases (perhaps not super likely, but impossible to rule out without huge effort), and more importantly, since 17.0.8 is clearly available (we're using it to build!), that constraint hurts no-one, as anyone on openjdk 17 will just get 17.0.8 then.

**Comment by mbiette** [comment]
Well… it hurts me, because I'm using 17.0.3 and the version 17.0.8 also comes with other dependencies that must be upgraded and some packages from conda-forge are not compatible yet.
Then maybe the package should not be pinned run as built, what is the rational to force the same jdk to build and run? In all my testing building it with jdk N and running it with a more recent version shouldn't pose any issue. (E.g build with jdk 11 vs run with jdk 17)
According to https://ant.apache.org/ the only runtime requirement is jdk >=8.

**Comment by h-vetinari** [comment]
> Well… it hurts me, because I'm using 17.0.3 and the version 17.0.8 also comes with other dependencies that must be upgraded and some packages from conda-forge are not compatible yet.

Can you be more specific? We should enable all packages to move to the latest patch version per major series (in fact, that's what all our migration infrastructure is for; it's possible or even likely that just some trivial rebuilds are missing).

**Comment by mbiette** [comment]
I hear you and will look into what details I can provide. But in any case the pinning of openjdk need to be addressed as it doesn't even seem to match the upstream project. Shouldn't only openjdk >=8 be the the ultimate runtime dependency and the build openjdk version aligned with the version used upstream? No max pin and no pin as built needed. Alternative idea, not even rebuilding and taking the upstream binary release.

**Comment by h-vetinari** [comment]
> Shouldn't only openjdk >=8 be the the ultimate runtime dependency and the build openjdk version aligned with the version used upstream?

That's only on source-level. Once you've compiled ant, you need a specific openjdk version (it's a bit of a special case). Which is why we (can) build it for all the different LTSes, and not just e.g. 17

**Comment by mbiette** [comment]
> That's only on source-level. Once you've compiled ant, you need a specific openjdk version (it's a bit of a special case)


Why is ant a special case? It seems to contradict this statement from the project main page:
> 1.10.x requires Java8 at **runtime**

And also the usual philosophy of Java which is compile once, run everywhere,
And my personal experience.

**Comment by mbiette** [comment]
For example why would it be different then another Java app like maven: https://github.com/conda-forge/maven-feedstock/blob/main/recipe/meta.yaml

**Comment by mbiette** [comment]
I'm updating the recipe to not have jdk variants anymore and I notice that in the build logs when building with openjdk 21 it mentions that:
`... Compiling Ant Classes with --release 8`
This shows that whatever the version of jdk used it will always build classes that will be compatible with jdk 8.

I tried manually building the package, which picked the latest version 21, then tested the resulting binary with jdk 8, 11, 17, and 21. The program worked with no issue.

**Comment by mbiette** [comment]
> Can you be more specific? We should enable all packages to move to the latest patch version per major series (in fact, that's what all our migration infrastructure is for; it's possible or even likely that just some trivial rebuilds are missing).

This is the combination that doesn't work:
`conda install -c conda-forge 'pyside2' 'ant' 'python-ldap' 'openjdk>=17'`

**Comment by h-vetinari** [comment]
> This is the combination that doesn't work:

The issue is with python-ldap, because for a long time that was not compatible with openldap>=2.5, and since that (2.6) is the only version we're building and migrating (e.g. for newer krb5), you get the conflicts.

Should be resolved by https://github.com/conda-forge/python-ldap-feedstock/pull/26

**Comment by mbiette** [comment]
Ok, thank you for that.
Regarding ant, what do you think about my change?

**Comment by mbiette** [comment]
@h-vetinari please, if you have some time can you review the pull request again? I updated it last week to reflect the way it is actually built and confirmed it by testing the resulting package with multiple version of openjdk.

**Comment by h-vetinari** [comment]
I still doubt that removing the dependence on the java version will work in all cases. Perhaps @xhochy knows some more. In any case, I merged the PR that was blocking the resolution so please try again (once the builds are available in 1-2 hours)

**Comment by xhochy** [comment]
> I still doubt that removing the dependence on the java version will work in all cases. Perhaps @xhochy knows some more. In any case, I merged the PR that was blocking the resolution so please try again (once the builds are available in 1-2 hours)

Sorry, no idea.

**Comment by h-vetinari** [comment]
@mbiette, sorry this fell off the radar - do you still need this?

**Comment by mbiette** [comment]
Hello, yes I still need it. Best regards

**Comment by h-vetinari** [comment]
Alright, let's try it then. Please let us know if anything breaks. I doubt apache ant has many users in conda-forge.

**Pull request merged**
