### PR TITLE
apache-ant v1.10.12 (redux)

### PR DESCRIPTION
**Pull request by h-vetinari**
Continuing from #3 

Closes #3 
Closes #2 
Closes #1

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge/help-java @conda-forge/openjdk
Hey all, I'm trying to revive this feedstock (which took on added importance now that the `ant` from defaults is not available anymore); linux and windows build fine, but osx fails with something I don't know how to debug:
```
BUILD FAILED
/Users/runner/miniforge3/conda-bld/apache-ant_1637484450813/work/build.xml:1529: The following error occurred while executing this line:
/Users/runner/miniforge3/conda-bld/apache-ant_1637484450813/work/build.xml:1033: Failed to set permissions on '/Users/runner/miniforge3/conda-bld/apache-ant_1637484450813/[...]/DISCLAIMER' due to /Users/runner/miniforge3/conda-bld/apache-ant_1637484450813/[...]/DISCLAIMER
```

Or in short:
```
Failed to set permissions on '[...]/DISCLAIMER' due to [...]/DISCLAIMER
```

PS. I need this in the context of https://github.com/conda-forge/pyjnius-feedstock/pull/29 -> https://github.com/conda-forge/staged-recipes/pull/14474 and added myself to maintainers.

**Comment by h-vetinari** [comment]
OK, I chased down [`build.xml:1033`](https://github.com/apache/ant/blame/rel/1.10.12/build.xml#L1033), but it's on a line that hasn't changed in years, and obviously this feedstock recipe worked for 1.10.9, which was way after that...

Also interesting is that the anaconda recipe seems to add the executable bit on osx [specifically](https://github.com/AnacondaRecipes/aggregate/blob/master/ant-feedstock/recipe/meta.yaml#L24) (but only at test time; which makes me wonder how their build passes)

**Comment by h-vetinari** [comment]
> but osx fails with something I don't know how to debug:

Lovely case of the [code](https://github.com/apache/ant/commit/c7d9b17b080fc5250fc05144322ecc3eef8a6e87) not matching with the [documentation](https://github.com/apache/ant/blob/rel/1.10.12/manual/install.html#L756) anymore, since... [checks notes] over 5 years..., but I figured it out at least

**Comment by h-vetinari** [comment]
@conda-forge/core
There's a gap between defaults & conda-forge here that became apparent** since we're now not using the defaults channel anymore; Anaconda [builds](https://github.com/AnacondaRecipes/aggregate/blob/master/ant-feedstock) `ant`, conda-forge builds `apache-ant`. Do we want to add a compatibility output here, or just a `run_constrained:` that evicts the defaults package?

** not on this feedstock, but for recipes depending on `ant`...

**Comment by h-vetinari** [comment]
Ping for opinions about how to handle `ant` in defaults vs `apache-ant` in conda-forge.
- do nothing
- rename package in conda-forge
- add compatibility output
- evict `ant` via `run_constrained`
- else?

**Comment by xhochy** [comment]
I would opt for "add compatibility output with `pin_subpackage(…, exact=True)`".

**Comment by h-vetinari** [comment]
Thanks for the input @xhochy! This is done & green now.

**Comment by h-vetinari** [comment]
ping @xhochy :)

**Review by xhochy — APPROVED** [review]

**Pull request merged**
